// app/layout.tsx

import "../styles/globals.css";
import React from "react";

export const metadata = {
	title: "My Next.js App",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>{/* You can add meta tags, links, or scripts here */}</head>
			<body>{children}</body>
		</html>
	);
}
